---
version: '3.7'
services:
  tomcat:
    image: drenobit:2.2.3
    container_name: d223test_renobit_container
    ports:
      - 8882:8080
    restart: on-failure
    depends_on:
      - db
    networks:
      - eb_d223test
    volumes:
      - d223test_tomcat_volume:/opt/tomcat/webapps/
  db:
    image: postgres:13
    container_name: d223test_postgre_container
    ports:
      - 5482:5432
    volumes:
      - d223test_pg_volume:/var/lib/postgresql/
    environment:
      POSTGRES_USER: "wemb"
      POSTGRES_PASSWORD: "wemb"
      POSTGRES_DB: "renobit"
      ALLOW_IP_RANGE: "0.0.0.0/0"
    restart: always
    networks:
      - eb_d223test

volumes:
  d223test_tomcat_volume:
  d223test_pg_volume:
networks:
  eb_d223test:





